# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instance_id', models.TextField()),
                ('network_id', models.TextField()),
                ('docker_image', models.TextField()),
                ('ports', models.TextField()),
                ('ip', models.TextField()),
                ('start_script', models.TextField()),
                ('state', models.TextField()),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('network_id', models.TextField()),
                ('cidr', models.TextField()),
                ('gateway', models.TextField()),
                ('security_group', models.TextField()),
                ('allocation_pools', models.TextField()),
                ('dns_nameservers', models.TextField()),
                ('connect_external', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('config', models.TextField()),
                ('description', models.TextField()),
                ('enable', models.PositiveSmallIntegerField(default=0)),
                ('type', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.AddField(
            model_name='network',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Provider'),
        ),
        migrations.AddField(
            model_name='app',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Provider'),
        ),
    ]
