# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='state',
        ),
        migrations.AddField(
            model_name='network',
            name='connect_external',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
